# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

# environment variables

PATH=/Applications/MacVim.app/Contents/bin:$PATH
export PATH

EDITOR=gvim
export EDITOR
