# .zshrc

# Source global definitions 
if [ -f /etc/zshrc ]; then
        . /etc/zshrc
fi

# User specific aliases and functions

alias ll='ls -Gl'
alias ls='ls -G'
alias la='ls -GA'

PATH="/Applications/MacVim.app/Contents/bin:$PATH"
export PATH

HISTSIZE=20000

EDITOR=gvim
export EDITOR

umask 0002
